version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=spring_auth
    volumes:
      - data:/var/lib/mysql

volumes:
  data: {}